//Loop to create 200 div elements

const gridContainer = document.querySelector(".grid");

// console.log(gridContainer);

for (let i = 0; i < 200; i++) {
  const gridElement = document.createElement("div");
  gridContainer.appendChild(gridElement);
}

let squares = Array.from(document.querySelectorAll(".grid div"));
// console.log(squares);
let count = 0;
const width = 10;

//for understanding
// for (let i = 0; i < 200; i++) {
//   squares[i].textContent = count;
//   count++;
// }

//In Tetris game we have only 4 major shapes:L,I,O,T,Z
//all other shapes are generated by rotating above four basic shapes

//so we have in total 4*5=20 shapes

// const shapeL = [0, width, 2 * width, 2 * width + 1];
// const shapeL = [width, width*2, width*2 + 1, width * 2+2 ];

const shapeL = [
  [1, width + 1, width * 2 + 1, 2],
  [width, width + 1, width + 2, width * 2 + 2],
  [1, width + 1, width * 2 + 1, width * 2],
  [width, width * 2, width * 2 + 1, width * 2 + 2],
];

const shapeZ = [
  [width + 1, width + 2, width * 2, width * 2 + 1],
  [0, width, width + 1, width * 2 + 1],
  [width + 1, width + 2, width * 2, width * 2 + 1],
  [0, width, width + 1, width * 2 + 1],
];

const shapeT = [
  [1, width, width + 1, width + 2],
  [1, width + 1, width + 2, width * 2 + 1],
  [width, width + 1, width + 2, width * 2 + 1],
  [1, width, width + 1, width * 2 + 1],
];

const shapeO = [
  [0, 1, width, width + 1],
  [0, 1, width, width + 1],
  [0, 1, width, width + 1],
  [0, 1, width, width + 1],
];

const shapeI = [
  [1, width + 1, width * 2 + 1, width * 3 + 1],
  [width, width + 1, width + 2, width + 3],
  [1, width + 1, width * 2 + 1, width * 3 + 1],
  [width, width + 1, width + 2, width + 3],
];

const AllShapes = [shapeL, shapeZ, shapeT, shapeO, shapeI];

//randomnly selecting shapes
let random = Math.floor(Math.random() * AllShapes.length);
let currentShape = AllShapes[random][0];

function draw() {
  currentShape.forEach((index) => {
    squares[index].style.background = "red";
  });
}

draw();
